### ISSUE TITLE
This is probably obvious

### ISSUE THREAD

**Issue by russ-sdg** [s-ichikawa/laravel-sendgrid-driver#136] opened 2020-10-06 16:10 UTC
I want to use sendgrid via the api for my Laravel website. The only use I have right now is if someone forgets their password with the standard auth Laravel setup.

I've installed laravel-sendgrid-driver and completed the configuration with my sendgrid info.

But when I request a password reset, I get this error:

GuzzleHttp\Exception\RequestException
cURL error 18: transfer closed with 88 bytes remaining to read (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.sendgrid.com/v3/mail/send

I'm guessing I've failed to do something. Can you point me in the right direction?

Thanks!

**Comment by russ-sdg** [comment] 2020-10-07 13:35
I have found the previous issues with the same error and tried the recommendations there, but to no effect. Specifically, I did composer update and I made the change in SendGridTransport to use version 1.0

**Comment by s-ichikawa** [comment] 2020-10-08 00:02
I have not encountered this error own env so far. so I don't be able to debug.
But I think this issue is about a more low layer. (e.g. config for OS, your infrastructure, etc...)

**Comment by russ-sdg** [comment] 2020-10-08 10:24
I followed the instructions on the SendGrid site for using PHP to send a message via their API and had no problems, so the underlying configuration seems to have everything it needs to connect to SendGrid and send a message. I will continue to dig into the Illuminate->Swift/Mailer->SendGridTransport->Guzzle stack to see where the problem is and will report back here if/when I find what is causing the problem.

Thank you for providing this tool. I wish it were as much plug-and-play as I need.

**Comment by josecabrerajr7** [comment] 2020-12-15 15:52
I have the same problem as well. Have anyone solve it?

**Comment by russ-sdg** [comment] 2020-12-15 16:20
No. I've given up on this plugin and will just follow the SendGrid api instructions. I wish this plugin were useful, but it doesn't work.

**Comment by josecabrerajr7** [comment] 2020-12-15 16:56
Thank you!

**Comment by yul-klj** [comment] 2020-12-24 03:31
Hi guys,
I had the same issue as well, running on app as below details:-
- laravel 5.4
- php 7.2
- this pacakge version 1.2.6

After debug and discovered that the `MAXIMUM_FILE_SIZE` was hard coded as CONST in file `s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridV3Transport.php`

Suggest to release the variable to be configuration externally, so that more flexible for users

**Comment by s-ichikawa** [comment] 2020-12-24 06:34
Oops! this MAXIMUM_FILE_SIZE is the limitation for API v2.
Certainly, I must fix it to the limitation of v3 or another way. (Maybe I'll fix it soon.)

But this validation work to cancel adding an attachment when over file size. and the issue said here is a file transfer was shorter or larger than expected.
So I'm not sure to resolve the issue after fix.

**Comment by Edwinws** [comment] 2020-12-24 07:34
@s-ichikawa One simple way to solve the problem is to make the max file size a configurable option in `config/services.php`, or use the hardcoded constant if it is not defined. Doing it this way will ensure backwards compatibility.

**Comment by s-ichikawa** [comment] 2020-12-24 19:37
I think it unnecessary to keep the wrong validation. So I want to delete it simply.
This change will bring about it will be able to send more big size requests. and will entrust the validation of the request to SendGrid.

**Comment by s-ichikawa** [comment] 2021-01-06 01:53
I merged the change and tagged 3.0.3 and 2.1.3. 
I hope to resolve this issue.

**Comment by s-ichikawa** [comment] 2021-02-06 14:01
Close this. but feel free to re-open if this problem continues to happen.

**Closed by s-ichikawa** 2021-02-06 14:01 UTC
